module.exports = {
    SYS_NOTIFY_UPDATE_SERVICE: 'SYS_NOTIFY_Update_Service',
    // SYS_NOTIFYTYPE
    SYS_NOTIFYTYPE_GETBYKEY_APP: 'SYS_NOTIFYTYPE_GetByKey_App',

    // SYS_NOTIFY
    SYS_NOTIFY_CREATE_APP: 'SYS_NOTIFY_Create_App',
    SYS_NOTIFY_GETLIST_APP: 'SYS_NOTIFY_GetList_App',
    SYS_NOTIFY_GETINFO_APP: 'SYS_NOTIFY_GetInfo_App',
    SYS_NOTIFY_CREATEMEMBERHOBBIESSUGGEST_APP: 'SYS_NOTIFY_CreateMemberHobbiesSuggest_App',

    // CRM_ACCOUNT
    CRM_ACCOUNT_UPDATECONNECTYCUBE_SERVICE: 'CRM_ACCOUNT_UpdateConnectyCube_Service',

    // SYS_ANNOUNCE
    SYS_ANNOUNCE_GETLISTTOPUSH_SERVICE: 'SYS_ANNOUNCE_GetListToPush_Service',
    SYS_ANNOUNCE_GETDETAILTOPUSH_SERVICE: 'SYS_ANNOUNCE_GetDetailToPush_Service',
    SYS_ANNOUNCE_UPDATETOPUSH_SERVICE: 'SYS_ANNOUNCE_UpdateToPush_Service',

    // SYS_MAIL 
    SYS_MAIL_GETDETAILTOPUSH_SERVICE: 'SYS_MAIL_GetDetailToPush_Service',
}